POST {{ host }}/auth/signup
Content-Type: application/json

{
  "name": "Robbie",
  "email": "robbie@mail.com",
  "password": "robbie1234",
  "phone": "010-0000-0000"
}
###

POST {{ host }}/auth/login
Content-Type: application/json

{
  "email": "robbie@mail.com",
  "password": "robbie1234"
}
###
